endpoints:
  - name: "Aionsoft Website"
    group: "Internal"
    url: https://aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Aionsoft Docs"
    group: "Internal"
    url: https://docs.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Aionsoft Analytics"
    group: "Internal"
    url: https://analytics.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Aionsoft Monitor"
    group: "Internal"
    url: https://monitor.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Aionsoft Authentication API"
    group: "Internal"
    url: https://auth1.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Aionsoft Authentication Admin"
    group: "Internal"
    url: https://auth2.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"