endpoints:
  - name: "Website"
    group: "Aionsoft"
    url: https://aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Docs"
    group: "Aionsoft"
    url: https://docs.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Analytics"
    group: "Aionsoft"
    url: https://analytics.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Monitor"
    group: "Aionsoft"
    url: https://monitor.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Authentication API"
    group: "Aionsoft"
    url: https://auth1.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: "Authentication Admin"
    group: "Aionsoft"
    url: https://auth2.aionsoft.io
    interval: 1m
    conditions:
      - "[STATUS] == 200"